[package]
name = "gitlab_issue"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_4"] }
gtk4 = { version = "0.10.0", features = ["v4_6"] }

[build-dependencies]
glib-build-tools = "0.21.0"
