[package]
name = "template-language"
version = "0.1.0"
edition = "2024"

[features]
std = []

[lib]
name = "template_language"

[dependencies]
libc = { version = "0.2.172", default-features = false }
libc_alloc = "1.0.7"

# [profile.dev]
# panic = "abort"

# [profile.release]
# panic = "abort"
